=== retverd/jira-progress-reporter/progress_reporter.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:annotation>
        <xs:documentation>
            All boolean elements are treated as "false" if element is missing.
        </xs:documentation>
    </xs:annotation>
    <xs:simpleType name="stringType">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    <xs:simpleType name="localeType">
        <xs:annotation>
            <xs:documentation>
                Locale names are based on http://docs.oracle.com/javase/1.5.0/docs/api/java/util/Locale.html.
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:enumeration value="ENGLISH"/>
            <xs:enumeration value="GERMAN"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="portType">
        <xs:restriction base="xs:positiveInteger">
            <xs:maxInclusive value="65535"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="cellType">
        <xs:restriction base="xs:string">
            <xs:pattern value="([A-Z])+([0-9])+"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="columnType">
        <xs:restriction base="xs:string">
            <xs:pattern value="([A-Z])+"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="rowType">
        <xs:restriction base="xs:nonNegativeInteger">
            <xs:maxInclusive value="1048576"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="proxyType">
        <xs:all>
            <xs:element type="stringType" name="host"/>
            <xs:element type="portType" name="port"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="listType">
        <xs:sequence>
            <xs:element type="stringType" name="entry" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="jiraType">
        <xs:all>
            <xs:element type="stringType" name="url"/>
            <xs:element type="xs:boolean" name="anonymous" minOccurs="0"/>
            <xs:element type="proxyType" name="proxy" minOccurs="0"/>
            <xs:element type="listType" name="projects" minOccurs="0"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="updateDateType">
        <xs:all>
            <xs:annotation>
                <xs:documentation>
                    Find syntax for element timePattern here: http://joda-time.sourceforge.net/apidocs/org/joda/time/format/DateTimeFormat.html.
                </xs:documentation>
            </xs:annotation>
            <xs:element type="cellType" name="cell"/>
            <xs:element type="stringType" name="timePattern"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="toHideType">
        <xs:annotation>
            <xs:documentation>
                All elements are treated as Java Regular Expressions, find syntax here: https://docs.oracle.com/javase/tutorial/essential/regex/.
            </xs:documentation>
        </xs:annotation>
        <xs:all>
            <xs:element type="cellType" name="issuePrefixCell" minOccurs="0"/>
            <xs:element type="cellType" name="affectedVersionCell" minOccurs="0"/>
            <xs:element type="cellType" name="componentsCell" minOccurs="0"/>
            <xs:element type="cellType" name="labelsCell" minOccurs="0"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="jqlQueryType">
        <xs:all>
            <xs:element type="cellType" name="cell"/>
            <xs:element type="xs:positiveInteger" name="searchStep"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="rootIssueType">
        <xs:all>
            <xs:element type="cellType" name="issueKeyCell"/>
            <xs:element type="listType" name="links"/>
            <xs:element type="xs:boolean" name="unfoldSubtasks"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="issueColumnsType">
        <xs:all>
            <xs:element type="columnType" name="summary" minOccurs="0"/>
            <xs:element type="columnType" name="key"/>
            <xs:element type="columnType" name="relation" minOccurs="0"/>
            <xs:element type="columnType" name="parentKey" minOccurs="0"/>
            <xs:element type="columnType" name="estimation" minOccurs="0"/>
            <xs:element type="columnType" name="spentTime" minOccurs="0"/>
            <xs:element type="columnType" name="remainingTime" minOccurs="0"/>
            <xs:element type="columnType" name="status" minOccurs="0"/>
            <xs:element type="columnType" name="afVersion" minOccurs="0"/>
            <xs:element type="columnType" name="dueDate" minOccurs="0"/>
            <xs:element type="columnType" name="components" minOccurs="0"/>
            <xs:element type="columnType" name="labels" minOccurs="0"/>
            <xs:element type="columnType" name="assignee" minOccurs="0"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="processingFlagsType">
        <xs:all>
            <xs:annotation>
                <xs:documentation>
                    Setting recalculateFormulas = true may lead to crash, see https://github.com/retverd/jira-progress-reporter/issues/1 for more details.
                </xs:documentation>
            </xs:annotation>
            <xs:element type="xs:boolean" name="issueSummaryUpdate"/>
            <xs:element type="xs:boolean" name="recalculateFormulas"/>
            <xs:element type="xs:boolean" name="autosizeColumns"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="reportNameType">
        <xs:all>
            <xs:annotation>
                <xs:documentation>
                    Find syntax for element timePattern here: http://joda-time.sourceforge.net/apidocs/org/joda/time/format/DateTimeFormat.html.
                </xs:documentation>
            </xs:annotation>
            <xs:element type="stringType" name="prefix" minOccurs="0"/>
            <xs:element type="stringType" name="timePattern" minOccurs="0"/>
            <xs:element type="stringType" name="suffix" minOccurs="0"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="reportType">
        <xs:all>
            <xs:annotation>
                <xs:documentation>
                    Find syntax for element timeTrackingFormat here: https://support.microsoft.com/en-us/kb/264372/,
                    https://support.office.com/en-US/article/create-a-custom-number-format-78f2a361-936b-4c03-8772-09fab54be7f4.
                </xs:documentation>
                <xs:documentation>
                    Find syntax for element dueDateFormat here:
                    https://support.office.com/en-ca/article/Format-a-date-the-way-you-want-8e10019e-d5d8-47a1-ba95-db95123d273e.
                </xs:documentation>
            </xs:annotation>
            <xs:element type="stringType" name="marker"/>
            <xs:element type="updateDateType" name="updateDate" minOccurs="0"/>
            <xs:element type="toHideType" name="toHide" minOccurs="0"/>
            <xs:element type="jqlQueryType" name="jqlQuery" minOccurs="0"/>
            <xs:element type="rootIssueType" name="rootIssue" minOccurs="0"/>
            <xs:element type="rowType" name="startProcessingRow"/>
            <xs:element type="issueColumnsType" name="issueColumns"/>
            <xs:element type="stringType" name="dueDateFormat" minOccurs="0"/>
            <xs:element type="stringType" name="timeTrackingFormat" minOccurs="0"/>
            <xs:element type="processingFlagsType" name="processingFlags" minOccurs="0"/>
            <xs:element type="reportNameType" name="reportName" minOccurs="0"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="configType">
        <xs:all>
            <xs:element type="jiraType" name="jira"/>
            <xs:element type="reportType" name="report"/>
            <xs:element type="localeType" name="locale" minOccurs="0"/>
        </xs:all>
    </xs:complexType>
    <xs:element name="config" type="configType"/>
</xs:schema>

=== retverd/jira-progress-reporter/src/test/resources/configs/missing_links_properties.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../progress_reporter.xsd">
    <jira>
        <url>https://jira.atlassian.com</url>
    </jira>
    <report>
        <marker># </marker>
        <!--Optional:-->
        <rootIssue>
            <issueKeyCell>D3</issueKeyCell>
            <links>
                <!--1 or more repetitions:-->
            </links>
            <unfoldSubtasks>true</unfoldSubtasks>
        </rootIssue>
        <startProcessingRow>6</startProcessingRow>
        <issueColumns>
            <key>B</key>
        </issueColumns>
    </report>
</config>

=== retverd/jira-progress-reporter/src/test/resources/configs/empty_report_name.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../progress_reporter.xsd">
    <jira>
        <url>https://jira.atlassian.com</url>
    </jira>
    <report>
        <marker>#</marker>
        <startProcessingRow>6</startProcessingRow>
        <issueColumns>
            <key>B</key>
        </issueColumns>
        <reportName/>
    </report>
</config>

=== retverd/jira-progress-reporter/src/test/resources/configs/all_properties.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../progress_reporter.xsd">
    <jira>
        <url>https://jira.atlassian.com</url>
        <!--Optional:-->
        <anonymous>true</anonymous>
        <!--Optional:-->
        <proxy>
            <host>127.0.0.1</host>
            <port>8080</port>
        </proxy>
        <!--Optional:-->
        <projects>
            <!--1 or more repetitions:-->
            <entry>PRJ1</entry>
            <entry>PRJ2</entry>
        </projects>
    </jira>
    <report>
        <marker>#</marker>
        <!--Optional:-->
        <updateDate>
            <cell>F4</cell>
            <timePattern>dd MMM yyyy HH:mm ZZ</timePattern>
        </updateDate>
        <!--Optional:-->
        <toHide>
            <!--Optional:-->
            <issuePrefixCell>A3</issuePrefixCell>
            <!--Optional:-->
            <affectedVersionCell>I3</affectedVersionCell>
            <!--Optional:-->
            <componentsCell>J3</componentsCell>
            <!--Optional:-->
            <labelsCell>K3</labelsCell>
        </toHide>
        <!--Optional:-->
        <jqlQuery>
            <cell>B3</cell>
            <searchStep>50</searchStep>
        </jqlQuery>
        <!--Optional:-->
        <rootIssue>
            <issueKeyCell>D3</issueKeyCell>
            <links>
                <!--1 or more repetitions:-->
                <entry>relates to</entry>
                <entry>is duplicated by</entry>
            </links>
            <unfoldSubtasks>true</unfoldSubtasks>
        </rootIssue>
        <startProcessingRow>6</startProcessingRow>
        <issueColumns>
            <!--Optional:-->
            <summary>A</summary>
            <key>B</key>
            <!--Optional:-->
            <relation>C</relation>
            <!--Optional:-->
            <parentKey>D</parentKey>
            <!--Optional:-->
            <estimation>E</estimation>
            <!--Optional:-->
            <spentTime>F</spentTime>
            <!--Optional:-->
            <remainingTime>G</remainingTime>
            <!--Optional:-->
            <status>H</status>
            <!--Optional:-->
            <afVersion>I</afVersion>
            <!--Optional:-->
            <components>J</components>
            <!--Optional:-->
            <labels>K</labels>
            <!--Optional:-->
            <assignee>L</assignee>
        </issueColumns>
        <!--Optional:-->
        <processingFlags>
            <issueSummaryUpdate>true</issueSummaryUpdate>
            <recalculateFormulas>false</recalculateFormulas>
            <autosizeColumns>false</autosizeColumns>
        </processingFlags>
        <!--Optional:-->
        <reportName>
            <!--Optional:-->
            <prefix>prefix_</prefix>
            <!--Optional:-->
            <timePattern>yyyy.MM.dd_HH_mm_ss</timePattern>
            <!--Optional:-->
            <suffix>_suffix</suffix>
        </reportName>
    </report>
</config>

=== retverd/jira-progress-reporter/src/test/resources/configs/mixed_boolean_properties.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../progress_reporter.xsd">
    <jira>
        <url>https://jira.atlassian.com</url>
        <!-- True as "true" -->
        <anonymous>true</anonymous>
    </jira>
    <report>
        <marker>#</marker>
        <processingFlags>
            <!-- True as "1" -->
            <issueSummaryUpdate>1</issueSummaryUpdate>
            <!-- False as "false" -->
            <recalculateFormulas>false</recalculateFormulas>
            <!-- False as "0" -->
            <autosizeColumns>0</autosizeColumns>
        </processingFlags>
        <startProcessingRow>6</startProcessingRow>
        <issueColumns>
            <key>B</key>
        </issueColumns>
        <timeTrackingFormat>0.00</timeTrackingFormat>
    </report>
</config>

=== retverd/jira-progress-reporter/src/test/resources/configs/only_column_cell_property.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../progress_reporter.xsd">
    <jira>
        <url>https://jira.atlassian.com</url>
    </jira>
    <report>
        <marker>#</marker>
        <updateDate>
            <cell>F</cell>
            <timePattern>dd MMM yyyy HH:mm ZZ</timePattern>
        </updateDate>
        <startProcessingRow>6</startProcessingRow>
        <issueColumns>
            <key>B</key>
        </issueColumns>
    </report>
</config>
